apiVersion: v1
kind: Namespace
metadata:
  name: homework
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8000;
          server_name  localhost;
          location / {
            root   /homework;
            index  index.html;
        }
          location ~ ^(/conf/)(\w)$ {
            try_files $uri $1/$2 =404;
        }
          location /metrics {
            alias   /homework/metrics.html;
            autoindex on;
        }

      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-conf
  namespace: homework
data:
  conf-file: |
    first.key=some-value-1
    second.key=some-value-2