apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-hw-4
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"