apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-cm-hw-4
  namespace: homework
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi