apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: homework
  labels:
    app: HW-1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: dormitory
      mountPath: /homework
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "rm /usr/share/nginx/html/index.html && ln -s /homework/index.html /usr/share/nginx/html/index.html"]
      preStop:
        exec:
          command: ["/bin/sh","-c","rm /homework/index.html"]
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: dormitory
      mountPath: "/init"
  dnsPolicy: Default
  volumes:
  - name: dormitory
    emptyDir: {}
